### ISSUE TITLE
How can I enable file imports?

### ISSUE THREAD

**Issue by georgiosd** [bugzpodder/yarn-workspace-cra#1]
Hey, thanks for this!

I search for a while but couldn't figure it out, maybe you can help?

I can make this work

lib/index.js:
```
import Api from './Api'
export { Api }
```
app/index.js:
```
import { Api } from 'shared'
```

But this doesn't work:

app/index.js:
```
import Api from shared/Api
```

Any idea why??

**Comment by bugzpodder** [comment]
You need to import Api from shared/dist/Api

**Comment by georgiosd** [comment]
Hm... how would I go about making it work without `dist`? Just point me in the right direction :)

**Comment by bugzpodder** [comment]
You cant without modifying webpack config.  If you do use create react app rewired you can add an alias to webpack  module resolves

**Comment by bugzpodder** [comment]
Or you can just export everything in index.js

**Comment by georgiosd** [comment]
That makes sense, thank you!
